openapi: 3.0.0
info:
  title: CS Messaging Web App
  version: 1.0.0
  description: Messaging web application for customer service at Branch
  contact:
    name: messaging
    email: messaging.email@example.com
paths:
  /messages:
    get:
      summary: Get all messages
      operationId: getMessages
      tags:
        - Messsages
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
    post:
      summary: Send a new message
      operationId: sendMessage
      tags:
        - Messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /messages/{id}:
    get:
      summary: Get a message by ID
      operationId: getMessage
      tags:
        - Messages
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the message
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          description: Message not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /simulate/receive-messages:
    get:
      summary: Simulate receiving multiple messages
      operationId: simulateReceiveMessages
      tags:
        - Simulation
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        time:
          type: string
        content:
          type: string
    Error:
      type: object
      properties:
        error:
          type: string

